import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F7FAFC",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#16423C",
    justifyContent: "space-between",
    paddingTop: 45,
    paddingBottom: 25,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  backButton: {
    paddingLeft: 20,
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: "center",
    paddingRight: 40,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
    letterSpacing: 1,
  },
  profileSection: {
    alignItems: "center",
    padding: 24,
    backgroundColor: "#fff",
    borderRadius: 24,
    marginHorizontal: 16,
    marginTop: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 12,
    borderWidth: 3,
    borderColor: "#FD9B63",
  },
  doctorName: {
    fontSize: 26,
    fontWeight: "700",
    marginBottom: 4,
    color: "#16423C",
  },
  specialization: {
    fontSize: 15,
    color: "#64748B",
    marginBottom: 4,
    fontWeight: "500",
  },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5E9",
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginTop: 8,
    marginBottom: 4,
  },
  ratingText: {
    fontSize: 16,
    fontWeight: "bold",
    marginHorizontal: 4,
    color: "#2E7D32",
  },
  reviewCount: {
    fontSize: 13,
    color: "#64748B",
  },
  section: {
    padding: 18,
    marginHorizontal: 10,
    marginTop: 10,
    backgroundColor: "#fff",
    borderRadius: 18,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#16423C",
  },
  aboutText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#334155",
  },
  workDayCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 18,
    margin: 8,
    minWidth: 150,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  workDayText: {
    color: "#22223B",
    fontWeight: "bold",
    fontSize: 18,
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  workHoursText: {
    color: "#4A5568",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 6,
  },
  activeWorkDayCard: {
    backgroundColor: "#22223B",
    borderColor: "#FD9B63",
    shadowColor: "#FD9B63",
    shadowOpacity: 0.15,
    elevation: 4,
  },
  dateText: {
    color: "#FD9B63",
    fontSize: 15,
    fontWeight: "bold",
    marginTop: 2,
  },
  bookButton: {
    backgroundColor: "#16423C",
    paddingVertical: 13,
    borderRadius: 20,
    alignSelf: "center",
    width: "45%",
    marginVertical: 10,
    elevation: 2,
  },
  clinicName: {
    color: "#FD9B63",
    fontSize: 16,
    fontWeight: "bold",
    marginVertical: 8,
  },
  // Add these new styles for the inline styles currently in index.js
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalScroll: {
    height: "100%",
    width: "100%",
    backgroundColor: "#fff",
  },
  modalContentContainer: {
    alignItems: "center",
  },
  modalHeader: {
    // Use styles.header for consistency, but allow override if needed
    // paddingTop and paddingBottom can be set inline if needed
  },
  modalBackButton: {
    // Use styles.backButton for consistency
  },
  modalHeaderTitleContainer: {
    // Use styles.headerTitleContainer for consistency
  },
  modalHeaderTitle: {
    // Use styles.headerTitle for consistency
  },
  clinicInfoSection: {
    width: "100%",
    marginBottom: 5,
    padding: 18,
  },
  addressCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    marginBottom: 6,
    paddingTop: 0,
  },
  phoneCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    marginBottom: 6,
    paddingTop: 0,
  },
  phoneButton: {
    backgroundColor: "#E2E8F0",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 6,
    marginBottom: 4,
  },
  phoneButtonSingle: {
    backgroundColor: "#E2E8F0",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  phoneButtonText: {
    color: "#16423C",
    fontWeight: "bold",
    fontSize: 15,
    textDecorationLine: "underline",
  },
  clinicCardsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "center",
  },
  clinicCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F7FAFC",
    borderRadius: 14,
    padding: 14,
    flex: 1,
    minWidth: 120,
    maxWidth: 140,
    margin: 4,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    elevation: 1,
  },
  priceCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F7FAFC",
    borderRadius: 14,
    padding: 14,
    flex: 1,
    minWidth: 100,
    maxWidth: 140,
    margin: 4,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    elevation: 1,
  },
  priceText: {
    color: "#2E7D32",
    fontWeight: "bold",
    fontSize: 15,
  },
  bookingDatesTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#FD9B63",
    marginBottom: 5,
    alignSelf: "center",
  },
  calendarSection: {
    width: "100%",
  },
  calendarRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 8,
  },
  calendarCard: {
    backgroundColor: "#F7FAFC",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    margin: 6,
    padding: 12,
    minWidth: 110,
    flex: 1,
    alignItems: "center",
    elevation: 1,
  },
  calendarCardSelected: {
    backgroundColor: "#FFF7F0",
    borderWidth: 2,
    borderColor: "#FD9B63",
  },
  calendarDayText: {
    fontWeight: "bold",
    fontSize: 15,
  },
  calendarDateText: {
    color: "#64748B",
    fontSize: 13,
  },
  calendarTimeButton: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginVertical: 2,
    alignSelf: "center",
    borderWidth: 1,
    minWidth: 90,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  calendarTimeButtonSelected: {
    backgroundColor: "#FD9B63",
    borderColor: "#FD9B63",
  },
  calendarTimeButtonUnselected: {
    backgroundColor: "#FFF7F0",
    borderColor: "#E2E8F0",
  },
  calendarTimeText: {
    fontSize: 14,
  },
  selectedDateIndicator: {
    backgroundColor: "#FFF7F0",
    borderColor: "#FD9B63",
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  selectedDateText: {
    color: "#FD9B63",
    fontWeight: "bold",
    fontSize: 12,
  },
  selectedDateValue: {
    color: "#16423C",
    fontWeight: "bold",
    fontSize: 12,
  },
  selectedTimeIcon: {
    marginLeft: 8,
    marginRight: 2,
  },
  ratingInput: {
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    minHeight: 44,
    backgroundColor: "#F8FAFC",
    fontSize: 15,
  },
});
