import { Dimensions } from "react-native";
import { primary } from "../../styles/colors";
export const styles = {
  container: {
    flex: 1,
    backgroundColor: "#E9EFEC",
  },
  backgroundContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    zIndex: -1,
  },
  header: {
    alignItems: "center",
    marginTop: 55,
    paddingHorizontal: 20,
    paddingBottom: 10,
    fontWeight: "bold",
  },
  greeting: {
    fontSize: 24,
    color: "#000",
  },
  subGreeting: {
    fontSize: 16,
    color: "#000",
    marginBottom: 10,
  },
  //Health Journey Banner
  healthCard: {
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: "#16423C",
    borderRadius: 20,
    height: 130,
    overflow: "hidden",
  },
  banner: {
    flex: 1,
    justifyContent: "center",
    // iOS shadow properties
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.5,
    shadowRadius: 7,
    // Android shadow property
    //elevation: 5,
  },
  CircleBackground: {
    backgroundColor: "#6A9C89",
    borderRadius: 55,
    width: 110,
    height: 110,
    position: "absolute",
    top: -1,
    left: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  bannerImage: {
    width: 120,
    height: 120,
    position: "absolute",
    bottom: -1,
  },
  bannerAllText: {
    flex: 1,
    marginLeft: 80,
    justifyContent: "center",
    alignItems: "center",
  },
  bannerText: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#FFF",
  },
  bannerSubText: {
    fontSize: 14,
    color: "#FD9B63",
    marginTop: 5,
  },
  // Search Bar
  searchContainer: {
    paddingHorizontal: 20,
    marginBottom: 10,
  },

  searchBarWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 25,
    elevation: 2,
  },

  searchBar: {
    flex: 1,
    paddingLeft: 20,
    height: 40,
    fontSize: 16,
    color: "#0000",
  },

  filterIconWrapper: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 15,
    height: 40,
  },
  //Services Section
  servicesSection: {
    marginVertical: 20,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  showMoreText: {
    color: "#FD9B63",
  },
  serviceCards: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  serviceCard: {
    backgroundColor: "#FFF",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    width: "45%",
    elevation: 2,
    // iOS shadow properties
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.2,
    shadowRadius: 9,
    // Android shadow property
    //elevation: 5,
  },
  cardText: {
    fontSize: 14,
    color: "#000",
    marginTop: 10,
  },
  // doctor section
  doctorSection: {
    marginVertical: 20,
    paddingHorizontal: 20,
  },
  AllRecords: {
    backgroundColor: "#fff",
    margin: "auto",
    marginBottom: 16,
    borderRadius: 12,
    elevation: 3,
    flexDirection: "column",
    // alignItems: "center",
    // padding: 15,
    width: "95%",
    height: 120,
    overflow: "hidden",
  },
  viewCard: {
    backgroundColor: "#6A9C89",
    margin: "auto",
    // marginBottom: 16,
    borderRadius: 12,
    elevation: 3,
    flexDirection: "column",
    // alignItems: "center",
    // padding: 15,
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  PastBookingCard: {
    backgroundColor: "#FFF",
    margin: "auto",
    marginBottom: 15,
    borderRadius: 10,
    elevation: 3,
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    width: "95%",
    height: 150,
    overflow: "hidden",
  },
  circleWrapper: {
    position: "absolute",
    top: -10,
    left: -10,
    zIndex: -1,
  },
  circleOne: {
    position: "absolute",
    width: 50,
    height: 60,
    backgroundColor: "#16423C",
    borderRadius: 55,
    top: 20,
    left: 27,
    opacity: 0.6,
    // iOS shadow properties
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.7,
    shadowRadius: 4,
    // Android shadow property
    //elevation: 5,
  },
  circleTwo: {
    position: "absolute",
    width: 70,
    height: 70,
    backgroundColor: "#16423C",
    borderRadius: 35,
    top: 15,
    left: 60,
  },
  doctorImage: {
    position: "absolute",
    width: 50,
    height: 50,
    top: 10,
    left: 5,
  },
  logo: {
    position: "absolute",
    width: 30,
    height: 50,
    top: 10,
    left: 16,
  },
  cardHeader: {
    display: "flex",
    flexDirection: "row",
    // fontSize: 10,
    // top: 12,
    // marginLeft: 50,
    // alignItems: "center",
    // backgroundColor: "#ffffff",
    backgroundColor: "#6A9C89",
    width: "100%",
    height: "30%",
    padding: 5,
    // marginLeft: 10,
  },
  doctorInfo: {
    justifyContent: "center",
    // flex: 1,
    padding: 16,
    // top: 20,
    width: "100%",
    backgroundColor: "#fcfcfcfc",
    height: "70%",
  },
  doctorName: {
    fontSize: 12,
    color: "#777777",
    marginBottom: 5,
  },
  doctorSpecialization: {
    fontSize: 14,
    color: "#333",
  },
  bottomNav: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#16423C",
    width: "100%",
    height: 60,
  },
  navButton: {
    alignItems: "center",
    paddingBottom: 15,
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "80%",
    backgroundColor: "#FFF",
    borderRadius: 10,
    padding: 20,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
  },
  filterOption: {
    padding: 10,
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#E9EFEC",
  },
  filterText: {
    fontSize: 16,
    color: "#333",
  },
  closeButton: {
    marginTop: 15,
    padding: 10,
    backgroundColor: "#FD9B63",
    borderRadius: 5,
  },
  closeButtonText: {
    color: "#FFF",
    fontSize: 16,
  },
  dropdown: {
    height: 40,
    width: "94%",
    borderWidth: 0.2,
    borderRadius: 12,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
    marginBottom: 10,
    marginLeft: 10,
  },
  
  // Edit Modal Styles
  editModalContainer: {
    width: 350,
    height: 650,
    backgroundColor: "#FFF",
    borderRadius: 15,
    overflow: "hidden",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  keyboardAvoidingView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#6A9C89",
    paddingHorizontal: 20,
    paddingVertical: 15,
    height: 60,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFF",
    flex: 1,
  },
  closeIcon: {
    padding: 5,
  },
  modalContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  currentDataSection: {
    marginVertical: 15,
    padding: 15,
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
  },
  editSection: {
    marginBottom: 20,
    paddingBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
  },
  currentDataText: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
  },
  modalFooter: {
    flexDirection: "row",
    padding: 15,
    backgroundColor: "#f9f9f9",
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
    alignItems: "center",
    justifyContent: "space-between",
    height: 70,
    paddingBottom: 15,
  },
  modalButton: {
    flex: 1,
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: "#ccc",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    marginRight: 8,
    height: 40,
  },
  cancelButtonText: {
    color: "#666",
    fontSize: 14,
    fontWeight: "bold",
  },
  updateButton: {
    flex: 1,
    marginLeft: 8,
    backgroundColor: "#6A9C89",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    height: 40,
  },
  
  // Array Field Styles
  arrayFieldContainer: {
    marginVertical: 10,
  },
  arrayFieldTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
  },
  arrayItemContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  arrayInputContainer: {
    flex: 1,
    marginRight: 10,
  },
  arrayInput: {
    width: "100%",
    minWidth: 200,
  },
  removeButton: {
    backgroundColor: "#ffe6e6",
    padding: 8,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e8f5e8",
    padding: 10,
    borderRadius: 8,
    marginTop: 5,
    borderWidth: 1,
    borderColor: "#6A9C89",
    borderStyle: "dashed",
  },
  addButtonText: {
    marginLeft: 8,
    color: "#6A9C89",
    fontWeight: "bold",
  },
  
  // Personal Info Styles
  inputGroup: {
    marginVertical: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginBottom: 5,
  },
  personalInput: {
    width: "100%",
    minWidth: 200,
  },
  selectInput: {
    width: "100%",
    minWidth: 200,
    marginVertical: 5,
  },
};
