import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E9EFEC",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    marginTop: 20,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
  },
  searchContainer: {
    paddingHorizontal: 20,
    marginBottom: 15,
    marginTop: 15,
  },
  searchBarWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 25,
    paddingHorizontal: 15,
    height: 45,
  },
  searchBar: {
    flex: 1,
    fontSize: 16,
  },
  filterContainer: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginBottom: 20,
    gap: 10,
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 25,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginRight: 10,
    width: "38%",
    height: 45,
  },
  filterButtonText: {
    flex: 1,
    textAlign: "center",
    fontSize: 13,
  },
  filterIconButton: {
    backgroundColor: "#FFF",
    borderRadius: 25,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  doctorsList: {
    paddingHorizontal: 20,
  },
  doctorCard: {
    backgroundColor: "#FFF",
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    flexDirection: "row",
  },
  doctorImage: {
    width: 70,
    height: 70,
    borderRadius: 15,
    marginRight: 15,
  },
  doctorInfo: {
    flex: 1,
  },
  serviceTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
  },
  doctorName: {
    color: "#666",
    fontSize: 14,
    marginBottom: 2,
  },
  specialization: {
    color: "#FD9B63",
    fontSize: 14,
    marginBottom: 2,
  },
  location: {
    color: "#999",
    fontSize: 12,
  },
  ratingContainer: {
    alignItems: "flex-end",
    justifyContent: "center",
    alignItems: "center",
  },
  ratingScore: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#000",
  },
  reviewCount: {
    fontSize: 12,
    color: "#666",
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(22, 66, 60, 0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "85%",
    maxHeight: "70%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#16423C",
    textAlign: "center",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    paddingBottom: 15,
  },
  modalItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalItemText: {
    fontSize: 16,
    color: "#333",
  },
  modalItemSelected: {
    backgroundColor: "#FD9B63",
    borderRadius: 12,
  },
  modalItemTextSelected: {
    color: "#fff",
    fontWeight: "bold",
  },
  closeButton: {
    marginTop: 20,
    width: "40%",
    backgroundColor: "#16423C",
    borderRadius: 20,
    padding: 15,
    alignItems: "center",
    alignSelf: "center",
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  sortDotIndicator: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#FD9B63",
    borderWidth: 1.5,
    borderColor: "#fff",
    zIndex: 2,
  },
});
