export const INITIAL_STATE = {
  step: 1,
  isDatePickerVisible: false,
  isDateOfChildPickerVisible: false,
  isPasswordVisible: false,
  formData: {
    userName: "",
    userPhone: "",
    userEmail: "",
    userPassword: "",
    personalRecords: {
      City: "",
      Area: "",
      userWeight: "",
      userHeight: "",
      DateOfBirth: "",
      emergencyContact: "",
      workName: "",
      workPlace: "",
      childrenNumber: "",
      birthDateOfFirstChild: "",
      smoking: "",
      alcohol: "",
      wifesNumber: "",
      petsTypes: [],
      familyStatus: "",
      Gender: "",
    },
  },
};
