export const INITIAL_STATE = {
  symptoms: [],
  head: [],
  eyes: [],
  chest: [],
  urinaryReproductive: [],
  musculoskeletal: [],
  general: [],
  pregnancy: [],
  digestive: [],
  throatMouth: [],
  skin: [],
  mental: [],
  stomach: [],
  limbs: [],
  prediction: "",
  specialist: "",
  isProcessing: false,
  loading: false,
  doctors: [],
};
