import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
    padding: 20,
  },
  robotContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  robotImage: {
    width: 160,
    height: 160,
  },
  symptomTagContainer: {
    backgroundColor: "#FD9B63",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  cardContainer: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  card: {
    backgroundColor: "#16423C",
    padding: 20,
    borderRadius: 30,
    width: "47%",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    marginVertical: 10,
  },
  cardHeader: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFF",
  },
  cardIcon: {
    fontSize: 20,
    color: "#FD9B63",
    marginBottom: 5,
  },

  buttonContainer: {
    marginTop: 20,
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  modalContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 20,
    padding: 25,
    marginHorizontal: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#2C3E50",
  },
  closeButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FD9B63",
  },
  scrollContainer: {
    height: "50%",
  },
  scrollContent: {
    flexGrow: 1,
    paddingVertical: 10,
  },
  selectedTag: {
    backgroundColor: "#FD9B63",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  unSelectedTag: {
    backgroundColor: "#E0E0E0",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    marginBottom: 10,
  },
  tagTextSelected: {
    color: "white",
    fontWeight: "bold",
  },
  tagTextUnSelected: {
    color: "#333",
    fontWeight: "bold",
  },
  sendButton: {
    backgroundColor: "#FD9B63", // bright orange, or use your primary color
    paddingVertical: 13,
    paddingHorizontal: 50,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6, // Android shadow
    shadowColor: "#FD9B63", // iOS shadow
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  sendButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
    letterSpacing: 1,
  },
  //----------------------------------------------------------------
  robotImageCheck: {
    width: 300,
    height: 300,
  },
  resultText: {
    fontSize: 18,
    marginBottom: 10,
    fontWeight: "600",
    color: "#16423C",
  },
  fullPageModal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E9EFEC",
  },
  //----------------------------------------------------------------
  doctorSection: {
    marginVertical: 20,
    paddingHorizontal: 20,
  },
  doctorCard: {
    backgroundColor: "#fff",
    marginVertical: 15,
    borderRadius: 10,
    elevation: 3,
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    width: Dimensions.get("window").width * 0.8,
    height: 140,
    overflow: "hidden",
  },
  circleWrapper: {
    position: "absolute",
    top: -10,
    left: -10,
    zIndex: -1,
  },
  circleOne: {
    position: "absolute",
    width: 110,
    height: 110,
    backgroundColor: "#6A9C89",
    borderRadius: 55,
    top: 30,
    left: 10,
    opacity: 0.6,
    // iOS shadow properties
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.7,
    shadowRadius: 4,
    // Android shadow property
    //elevation: 5,
  },
  circleTwo: {
    position: "absolute",
    width: 70,
    height: 70,
    backgroundColor: "#FD9B63",
    borderRadius: 35,
    top: 15,
    left: 60,
  },
  doctorImage: {
    position: "absolute",
    width: 100,
    height: 150,
  },
  doctorInfo: {
    justifyContent: "center",
    flex: 1,
    paddingLeft: 110,
  },
  doctorName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
  doctorSpecialization: {
    fontSize: 14,
    color: "#666",
  },
  bottomNav: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#16423C",
    width: "100%",
    height: 60,
  },
  navButton: {
    alignItems: "center",
    paddingBottom: 15,
  },
  doctorCard: {
    backgroundColor: "#FFF",
    marginRight: 0,
    borderRadius: 18,
    width: 300,
    height: 145,
    padding: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
    overflow: "hidden",
    position: "relative",
  },
  greenWave: {
    position: "absolute",
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(106, 156, 137, 0.08)",
    top: -220,
    right: -100,
  },
  orangeBubble: {
    position: "absolute",
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(253, 155, 99, 0.15)",
    bottom: -40,
    left: -30,
  },
  greenBar: {
    position: "absolute",
    width: 8,
    height: 60,
    backgroundColor: "#6A9C89",
    borderRadius: 4,
    top: 15,
    left: 15,
  },
  orangeDot: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#FD9B63",
    opacity: 0.6,
    top: 80,
    left: 9,
  },
  doctorImageBorder: {
    position: "absolute",
    width: 74,
    height: 74,
    borderRadius: 37,
    borderWidth: 2,
    borderColor: "#6A9C89",
    borderStyle: "dashed",
    top: 12,
    right: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  doctorImageContainer: {
    width: 65,
    height: 65,
    borderRadius: 32.5,
    overflow: "hidden",
    backgroundColor: "#F7F7F7",
    borderWidth: 2,
    borderColor: "#FFF",
  },
  doctorImage: {
    width: "100%",
    height: "100%",
  },
  doctorContent: {
    padding: 15,
    paddingLeft: 35,
  },
  doctorName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
    marginTop: 5,
    marginBottom: 5,
  },
  doctorInfo: {
    width: "65%",
  },
  doctorSpecialty: {
    fontSize: 13,
    color: "#6A9C89",
    fontWeight: "600",
    marginBottom: 10,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  infoText: {
    fontSize: 11,
    color: "#666",
    marginLeft: 4,
  },
  statusBadge: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 26,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    backgroundColor: "rgba(106, 156, 137, 0.1)",
  },
  starContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 12,
    color: "#FD9B63",
    fontWeight: "600",
    marginLeft: 3,
  },
  availableText: {
    fontSize: 12,
    color: "#6A9C89",
    fontWeight: "500",
  },
  doctorTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
    marginBottom: 8,
  },
  doctorTag: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "#F0F7F4",
    borderRadius: 6,
    marginRight: 6,
    marginBottom: 6,
  },
  doctorTagText: {
    color: "#6A9C89",
    fontSize: 9,
    fontWeight: "600",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    position: "absolute",
    right: 16,
    bottom: 12,
    backgroundColor: "#FFF9F0",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  availabilityBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5F0",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  availabilityText: {
    fontSize: 10,
    color: "#6A9C89",
    fontWeight: "500",
    marginLeft: 3,
  },
  doctorHeader: {
    flexDirection: "row",
    padding: 15,
  },
  doctorInfoContainer: {
    flex: 1,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  starRating: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 10,
  },
  rating: {
    color: "#FD9B63",
    fontSize: 12,
    fontWeight: "500",
    marginLeft: 3,
  },
  verifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5F0",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  verifiedText: {
    color: "#6A9C89",
    fontSize: 10,
    fontWeight: "500",
    marginLeft: 2,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 3,
  },
  locationIcon: {
    marginRight: 4,
  },
  locationText: {
    fontSize: 12,
    color: "#666",
  },
  experienceText: {
    fontSize: 12,
    color: "#666",
    marginBottom: 6,
  },
  doctorFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 0,
  },
  footerItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  footerText: {
    fontSize: 11,
    color: "#666",
    marginLeft: 4,
  },
  specialtyBadge: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#6A9C89",
    paddingVertical: 6,
    paddingHorizontal: 15,
    borderTopRightRadius: 15,
  },
  specialtyText: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "500",
  },
  bookButton: {
    backgroundColor: "#FD9B63",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginTop: 10,
  },
  bookButtonText: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "600",
  },
});
