export const INITIAL_STATE = {
  allAppointments: [],
  upcomingAppointments: [],
  pastAppointments: [],
  filteredAppointments: [],
  allAppointmentsStatus: [],
  selectedStatus: "All",
  selectedAppointmentType: "",
  searchQuery: "",
  sortType: "date",
  sortOrder: "desc",
  showSortModal: false,
  loading: false,
  error: null,
  receiptData: null,
  showReceiptModal: false,
};
