import { Dimensions, StyleSheet } from "react-native";
import { primary } from "../../styles/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  // Search Bar Styles
  searchContainer: {
    paddingHorizontal: 20,
    marginBottom: 15,
    marginTop: 0,
  },
  searchBarWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 25,
    paddingHorizontal: 15,
    height: 45,
  },
  searchBar: {
    flex: 1,
    fontSize: 16,
  },
  // Enhanced Filter Container
  filtersContainer: {
    paddingHorizontal: 0,
    marginBottom: 20,
    marginTop: 15,
  },
  // New: All filters in one row
  allFiltersRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    gap: 10,
  },
  // Status filters scroll view
  statusFiltersScroll: {
    flex: 1,
    marginRight: 10,
  },
  filterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  filterContainer: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  filterButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: "#FFF",
    marginRight: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  activeFilterButton: {
    backgroundColor: "#16423C",
    shadowColor: "#16423C",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  filterButtonText: {
    fontSize: 13,
    color: "#666",
    fontWeight: "600",
  },
  activeFilterButtonText: {
    color: "#FFF",
  },
  // Appointment Type Filter
  typeFilterButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 25,
    paddingHorizontal: 15,
    paddingVertical: 10,
    minWidth: 80,
    height: 40,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  typeFilterButtonText: {
    flex: 1,
    textAlign: "center",
    fontSize: 12,
    color: "#666",
  },
  // Sort Button
  sortIconButton: {
    backgroundColor: "#FFF",
    borderRadius: 25,
    paddingHorizontal: 12,
    paddingVertical: 10,
    height: 40,
    width: 40,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  sortDotIndicator: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#FD9B63",
    borderWidth: 1.5,
    borderColor: "#fff",
    zIndex: 2,
  },
  // Sort Modal Styles
  sortModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(22, 66, 60, 0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  sortModalContent: {
    width: "85%",
    maxHeight: "70%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  sortModalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#16423C",
    textAlign: "center",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    paddingBottom: 15,
  },
  sortModalItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sortModalItemText: {
    fontSize: 16,
    color: "#333",
  },
  sortModalItemSelected: {
    backgroundColor: "#FD9B63",
    borderRadius: 12,
  },
  sortModalItemTextSelected: {
    color: "#fff",
    fontWeight: "bold",
  },
  sortCloseButton: {
    marginTop: 20,
    width: "40%",
    backgroundColor: "#16423C",
    borderRadius: 20,
    padding: 15,
    alignItems: "center",
    alignSelf: "center",
  },
  sortCloseButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  // Type Filter Modal Styles
  typeModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(22, 66, 60, 0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  typeModalContent: {
    width: "85%",
    maxHeight: "70%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  typeModalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#16423C",
    textAlign: "center",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    paddingBottom: 15,
  },
  typeModalItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  typeModalItemText: {
    fontSize: 16,
    color: "#333",
  },
  typeModalItemSelected: {
    backgroundColor: "#FD9B63",
    borderRadius: 12,
  },
  typeModalItemTextSelected: {
    color: "#fff",
    fontWeight: "bold",
  },
  typeCloseButton: {
    marginTop: 20,
    width: "40%",
    backgroundColor: "#16423C",
    borderRadius: 20,
    padding: 15,
    alignItems: "center",
    alignSelf: "center",
  },
  typeCloseButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  appointmentsContainer: {
    padding: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    color: "#DC2626",
    fontSize: 16,
    textAlign: "center",
  },
  actionButton: {
    marginTop: 12,
    borderRadius: 12,
    paddingVertical: 10,
    backgroundColor: "#F0F4F8",
  },
  actionButtonText: {
    color: "#16423C",
    fontWeight: "600",
    textAlign: "center",
  },
  appointmentCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    marginBottom: 20,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    borderWidth: 0,
    transform: [{ scale: 1 }],
  },
  cardHeader: {
    paddingTop: 20,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "700",
  },
  cardContent: {
    padding: 16,
  },
  doctorInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  doctorImage: {
    width: 64,
    height: 64,
    borderRadius: 32,
    marginRight: 16,
    backgroundColor: "#E8ECF1",
  },
  doctorDetails: {
    flex: 1,
  },
  doctorName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A202C",
    marginBottom: 4,
  },
  specialty: {
    fontSize: 14,
    color: "#718096",
  },
  appointmentDetails: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  detailText: {
    fontSize: 13,
    color: "#4A5568",
    marginLeft: 8,
  },
  cancelButton: {
    marginTop: 16,
    backgroundColor: "#FEE2E2",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FECACA",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: {
    color: "#DC2626",
    fontSize: 13,
    fontWeight: "600",
    marginLeft: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    maxHeight: "80%",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#16423C",
  },
  receiptContent: {
    paddingBottom: 40,
  },
  receiptSection: {
    backgroundColor: "#F8FAFC",
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#16423C",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    paddingBottom: 10,
  },
  receiptRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  receiptLabel: {
    fontSize: 15,
    color: "#64748B",
    flex: 1,
  },
  receiptValue: {
    fontSize: 15,
    color: "#334155",
    fontWeight: "500",
    flex: 2,
    textAlign: "right",
  },
  paymentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
});
