export const INITIAL_STATE = {
  email: "",
  password: "",
  loading: false,
  otp: "",
  otpAsync: "",
  formData: {
    userName: "",
    userNameValidationText: "",
    userPhone: "",
    userPhoneValidationText: "",
    userEmail: "",
    userEmailValidationText: "",
    userPassword: "",
    userPasswordValidationText: "",
    City: "",
    CityValidationText: "",
    Area: "",
    AreaValidationText: "",
    Gender: "",
    GenderValidationText: "",
    userWeight: "",
    userWeightValidationText: "",
    userHeight: "",
    userHeightValidationText: "",
    DateofBirth: "",
    DateofBirthValidationText: "",
    BooldType: "",
    BooldTypeValidationText: "",
    // allergy: "",
  },
  reEnterYourPassword: "",
  reEnterYourPasswordValidationText: "",
  currentStep: 1,
  isDatePickerVisible: false,
};
